/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:46 PM CET
//

package net.datasiel.par.jaxb.stato;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DatiVolumeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DatiVolumeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NomeVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatoVolume" type="{}TokenNonVuotoType"/>
 *         &lt;element name="DataAperturaVolume" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DataChiusuraVolume" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DataFirmaVolume" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DocumentiContenuti" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentoContenuto" type="{}DocumentoContenutoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiVolumeType", propOrder = { "idVolume", "nomeVolume", "statoVolume", "dataAperturaVolume",
        "dataChiusuraVolume", "dataFirmaVolume", "documentiContenuti" })
public class DatiVolumeType {

    @XmlElement(name = "IdVolume", required = true)
    protected String idVolume;
    @XmlElement(name = "NomeVolume", required = true)
    protected String nomeVolume;
    @XmlElement(name = "StatoVolume", required = true)
    protected String statoVolume;
    @XmlElement(name = "DataAperturaVolume")
    protected XMLGregorianCalendar dataAperturaVolume;
    @XmlElement(name = "DataChiusuraVolume")
    protected XMLGregorianCalendar dataChiusuraVolume;
    @XmlElement(name = "DataFirmaVolume")
    protected XMLGregorianCalendar dataFirmaVolume;
    @XmlElement(name = "DocumentiContenuti")
    protected DatiVolumeType.DocumentiContenuti documentiContenuti;

    /**
     * Gets the value of the idVolume property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIdVolume() {
        return idVolume;
    }

    /**
     * Sets the value of the idVolume property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setIdVolume(String value) {
        this.idVolume = value;
    }

    /**
     * Gets the value of the nomeVolume property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNomeVolume() {
        return nomeVolume;
    }

    /**
     * Sets the value of the nomeVolume property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setNomeVolume(String value) {
        this.nomeVolume = value;
    }

    /**
     * Gets the value of the statoVolume property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatoVolume() {
        return statoVolume;
    }

    /**
     * Sets the value of the statoVolume property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setStatoVolume(String value) {
        this.statoVolume = value;
    }

    /**
     * Gets the value of the dataAperturaVolume property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataAperturaVolume() {
        return dataAperturaVolume;
    }

    /**
     * Sets the value of the dataAperturaVolume property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataAperturaVolume(XMLGregorianCalendar value) {
        this.dataAperturaVolume = value;
    }

    /**
     * Gets the value of the dataChiusuraVolume property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataChiusuraVolume() {
        return dataChiusuraVolume;
    }

    /**
     * Sets the value of the dataChiusuraVolume property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataChiusuraVolume(XMLGregorianCalendar value) {
        this.dataChiusuraVolume = value;
    }

    /**
     * Gets the value of the dataFirmaVolume property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataFirmaVolume() {
        return dataFirmaVolume;
    }

    /**
     * Sets the value of the dataFirmaVolume property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataFirmaVolume(XMLGregorianCalendar value) {
        this.dataFirmaVolume = value;
    }

    /**
     * Gets the value of the documentiContenuti property.
     *
     * @return possible object is {@link DatiVolumeType.DocumentiContenuti }
     *
     */
    public DatiVolumeType.DocumentiContenuti getDocumentiContenuti() {
        return documentiContenuti;
    }

    /**
     * Sets the value of the documentiContenuti property.
     *
     * @param value
     *            allowed object is {@link DatiVolumeType.DocumentiContenuti }
     *
     */
    public void setDocumentiContenuti(DatiVolumeType.DocumentiContenuti value) {
        this.documentiContenuti = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentoContenuto" type="{}DocumentoContenutoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "documentoContenuto" })
    public static class DocumentiContenuti {

        @XmlElement(name = "DocumentoContenuto", required = true)
        protected List<DocumentoContenutoType> documentoContenuto;

        /**
         * Gets the value of the documentoContenuto property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the documentoContenuto property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getDocumentoContenuto().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DocumentoContenutoType }
         *
         *
         */
        public List<DocumentoContenutoType> getDocumentoContenuto() {
            if (documentoContenuto == null) {
                documentoContenuto = new ArrayList<DocumentoContenutoType>();
            }
            return this.documentoContenuto;
        }

    }

}
