/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:46 PM CET
//

package net.datasiel.par.jaxb.stato;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DocumentoContenutoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentoContenutoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="URNDocumento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataVersamento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TipoConservazione" type="{}TipoConservazioneType" minOccurs="0"/>
 *         &lt;element name="SistemaDiMigrazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentoContenutoType", propOrder = { "urnDocumento", "dataVersamento", "tipoConservazione",
        "sistemaDiMigrazione" })
public class DocumentoContenutoType {

    @XmlElement(name = "URNDocumento", required = true)
    protected String urnDocumento;
    @XmlElement(name = "DataVersamento", required = true)
    protected XMLGregorianCalendar dataVersamento;
    @XmlElement(name = "TipoConservazione")
    protected TipoConservazioneType tipoConservazione;
    @XmlElement(name = "SistemaDiMigrazione")
    protected String sistemaDiMigrazione;

    /**
     * Gets the value of the urnDocumento property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getURNDocumento() {
        return urnDocumento;
    }

    /**
     * Sets the value of the urnDocumento property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setURNDocumento(String value) {
        this.urnDocumento = value;
    }

    /**
     * Gets the value of the dataVersamento property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataVersamento() {
        return dataVersamento;
    }

    /**
     * Sets the value of the dataVersamento property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataVersamento(XMLGregorianCalendar value) {
        this.dataVersamento = value;
    }

    /**
     * Gets the value of the tipoConservazione property.
     *
     * @return possible object is {@link TipoConservazioneType }
     *
     */
    public TipoConservazioneType getTipoConservazione() {
        return tipoConservazione;
    }

    /**
     * Sets the value of the tipoConservazione property.
     *
     * @param value
     *            allowed object is {@link TipoConservazioneType }
     *
     */
    public void setTipoConservazione(TipoConservazioneType value) {
        this.tipoConservazione = value;
    }

    /**
     * Gets the value of the sistemaDiMigrazione property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSistemaDiMigrazione() {
        return sistemaDiMigrazione;
    }

    /**
     * Sets the value of the sistemaDiMigrazione property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setSistemaDiMigrazione(String value) {
        this.sistemaDiMigrazione = value;
    }

}
