/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 03:12:46 PM CET 
//

package net.datasiel.par.jaxb.stato;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EsitoChiamataWSType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EsitoChiamataWSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VersioneWSCorretta" type="{}ECEsitoPosNegType"/>
 *         &lt;element name="CredenzialiOperatore" type="{}ECEsitoPosNegType"/>
 *         &lt;element name="IdentificazioneVersatore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IdentificazioneChiave" type="{}ECEsitoPosNegType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EsitoChiamataWSType", propOrder = { "versioneWSCorretta", "credenzialiOperatore",
        "identificazioneVersatore", "identificazioneChiave" })
public class EsitoChiamataWSType {

    @XmlElement(name = "VersioneWSCorretta", required = true)
    protected ECEsitoPosNegType versioneWSCorretta;
    @XmlElement(name = "CredenzialiOperatore", required = true)
    protected ECEsitoPosNegType credenzialiOperatore;
    @XmlElement(name = "IdentificazioneVersatore")
    protected String identificazioneVersatore;
    @XmlElement(name = "IdentificazioneChiave")
    protected ECEsitoPosNegType identificazioneChiave;

    /**
     * Gets the value of the versioneWSCorretta property.
     * 
     * @return possible object is {@link ECEsitoPosNegType }
     * 
     */
    public ECEsitoPosNegType getVersioneWSCorretta() {
        return versioneWSCorretta;
    }

    /**
     * Sets the value of the versioneWSCorretta property.
     * 
     * @param value
     *            allowed object is {@link ECEsitoPosNegType }
     * 
     */
    public void setVersioneWSCorretta(ECEsitoPosNegType value) {
        this.versioneWSCorretta = value;
    }

    /**
     * Gets the value of the credenzialiOperatore property.
     * 
     * @return possible object is {@link ECEsitoPosNegType }
     * 
     */
    public ECEsitoPosNegType getCredenzialiOperatore() {
        return credenzialiOperatore;
    }

    /**
     * Sets the value of the credenzialiOperatore property.
     * 
     * @param value
     *            allowed object is {@link ECEsitoPosNegType }
     * 
     */
    public void setCredenzialiOperatore(ECEsitoPosNegType value) {
        this.credenzialiOperatore = value;
    }

    /**
     * Gets the value of the identificazioneVersatore property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentificazioneVersatore() {
        return identificazioneVersatore;
    }

    /**
     * Sets the value of the identificazioneVersatore property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdentificazioneVersatore(String value) {
        this.identificazioneVersatore = value;
    }

    /**
     * Gets the value of the identificazioneChiave property.
     * 
     * @return possible object is {@link ECEsitoPosNegType }
     * 
     */
    public ECEsitoPosNegType getIdentificazioneChiave() {
        return identificazioneChiave;
    }

    /**
     * Sets the value of the identificazioneChiave property.
     * 
     * @param value
     *            allowed object is {@link ECEsitoPosNegType }
     * 
     */
    public void setIdentificazioneChiave(ECEsitoPosNegType value) {
        this.identificazioneChiave = value;
    }

}
