/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 03:12:46 PM CET 
//

package net.datasiel.par.jaxb.stato;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.datasiel.par.jaxb.stato package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.datasiel.par.jaxb.stato
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProfiloUnitaDocumentariaType }
     * 
     */
    public ProfiloUnitaDocumentariaType createProfiloUnitaDocumentariaType() {
        return new ProfiloUnitaDocumentariaType();
    }

    /**
     * Create an instance of {@link StrutturaType }
     * 
     */
    public StrutturaType createStrutturaType() {
        return new StrutturaType();
    }

    /**
     * Create an instance of {@link DocumentoCollegatoType }
     * 
     */
    public DocumentoCollegatoType createDocumentoCollegatoType() {
        return new DocumentoCollegatoType();
    }

    /**
     * Create an instance of {@link ComponenteType }
     * 
     */
    public ComponenteType createComponenteType() {
        return new ComponenteType();
    }

    /**
     * Create an instance of {@link ComponenteType.SottoComponenti }
     * 
     */
    public ComponenteType.SottoComponenti createComponenteTypeSottoComponenti() {
        return new ComponenteType.SottoComponenti();
    }

    /**
     * Create an instance of {@link StrutturaType.Componenti }
     * 
     */
    public StrutturaType.Componenti createStrutturaTypeComponenti() {
        return new StrutturaType.Componenti();
    }

    /**
     * Create an instance of {@link ProfiloDocumentoType }
     * 
     */
    public ProfiloDocumentoType createProfiloDocumentoType() {
        return new ProfiloDocumentoType();
    }

    /**
     * Create an instance of {@link FascicoloType }
     * 
     */
    public FascicoloType createFascicoloType() {
        return new FascicoloType();
    }

    /**
     * Create an instance of {@link DocumentoContenutoType }
     * 
     */
    public DocumentoContenutoType createDocumentoContenutoType() {
        return new DocumentoContenutoType();
    }

    /**
     * Create an instance of {@link PCVolumeType }
     * 
     */
    public PCVolumeType createPCVolumeType() {
        return new PCVolumeType();
    }

    /**
     * Create an instance of {@link DatiVolumeType.DocumentiContenuti }
     * 
     */
    public DatiVolumeType.DocumentiContenuti createDatiVolumeTypeDocumentiContenuti() {
        return new DatiVolumeType.DocumentiContenuti();
    }

    /**
     * Create an instance of {@link EsitoGeneraleType }
     * 
     */
    public EsitoGeneraleType createEsitoGeneraleType() {
        return new EsitoGeneraleType();
    }

    /**
     * Create an instance of {@link DatiUnitaDocType.Volumi }
     * 
     */
    public DatiUnitaDocType.Volumi createDatiUnitaDocTypeVolumi() {
        return new DatiUnitaDocType.Volumi();
    }

    /**
     * Create an instance of {@link DatiRifVolumeType }
     * 
     */
    public DatiRifVolumeType createDatiRifVolumeType() {
        return new DatiRifVolumeType();
    }

    /**
     * Create an instance of {@link DatiVolumeType }
     * 
     */
    public DatiVolumeType createDatiVolumeType() {
        return new DatiVolumeType();
    }

    /**
     * Create an instance of {@link DatiSpecificiType }
     * 
     */
    public DatiSpecificiType createDatiSpecificiType() {
        return new DatiSpecificiType();
    }

    /**
     * Create an instance of {@link UnitaDocumentaria.Allegati }
     * 
     */
    public UnitaDocumentaria.Allegati createUnitaDocumentariaAllegati() {
        return new UnitaDocumentaria.Allegati();
    }

    /**
     * Create an instance of {@link IndiceProveConservazione.Volumi }
     * 
     */
    public IndiceProveConservazione.Volumi createIndiceProveConservazioneVolumi() {
        return new IndiceProveConservazione.Volumi();
    }

    /**
     * Create an instance of {@link SCVersatoreType }
     * 
     */
    public SCVersatoreType createSCVersatoreType() {
        return new SCVersatoreType();
    }

    /**
     * Create an instance of {@link ProfiloArchivisticoType }
     * 
     */
    public ProfiloArchivisticoType createProfiloArchivisticoType() {
        return new ProfiloArchivisticoType();
    }

    /**
     * Create an instance of {@link DocumentoCollegatoType.DocumentoCollegato }
     * 
     */
    public DocumentoCollegatoType.DocumentoCollegato createDocumentoCollegatoTypeDocumentoCollegato() {
        return new DocumentoCollegatoType.DocumentoCollegato();
    }

    /**
     * Create an instance of {@link UnitaDocumentaria.Annessi }
     * 
     */
    public UnitaDocumentaria.Annessi createUnitaDocumentariaAnnessi() {
        return new UnitaDocumentaria.Annessi();
    }

    /**
     * Create an instance of {@link CamiciaFascicoloType }
     * 
     */
    public CamiciaFascicoloType createCamiciaFascicoloType() {
        return new CamiciaFascicoloType();
    }

    /**
     * Create an instance of {@link UnitaDocumentaria.Annotazioni }
     * 
     */
    public UnitaDocumentaria.Annotazioni createUnitaDocumentariaAnnotazioni() {
        return new UnitaDocumentaria.Annotazioni();
    }

    /**
     * Create an instance of {@link ChiaveType }
     * 
     */
    public ChiaveType createChiaveType() {
        return new ChiaveType();
    }

    /**
     * Create an instance of {@link DocumentoType.Volumi }
     * 
     */
    public DocumentoType.Volumi createDocumentoTypeVolumi() {
        return new DocumentoType.Volumi();
    }

    /**
     * Create an instance of {@link StatoConservazione }
     * 
     */
    public StatoConservazione createStatoConservazione() {
        return new StatoConservazione();
    }

    /**
     * Create an instance of {@link DocumentoType }
     * 
     */
    public DocumentoType createDocumentoType() {
        return new DocumentoType();
    }

    /**
     * Create an instance of {@link DatiUnitaDocType }
     * 
     */
    public DatiUnitaDocType createDatiUnitaDocType() {
        return new DatiUnitaDocType();
    }

    /**
     * Create an instance of {@link UnitaDocumentaria }
     * 
     */
    public UnitaDocumentaria createUnitaDocumentaria() {
        return new UnitaDocumentaria();
    }

    /**
     * Create an instance of {@link DatiFiscaliType }
     * 
     */
    public DatiFiscaliType createDatiFiscaliType() {
        return new DatiFiscaliType();
    }

    /**
     * Create an instance of {@link EsitoChiamataWSType }
     * 
     */
    public EsitoChiamataWSType createEsitoChiamataWSType() {
        return new EsitoChiamataWSType();
    }

    /**
     * Create an instance of {@link IndiceProveConservazione }
     * 
     */
    public IndiceProveConservazione createIndiceProveConservazione() {
        return new IndiceProveConservazione();
    }

    /**
     * Create an instance of {@link SottoComponenteType }
     * 
     */
    public SottoComponenteType createSottoComponenteType() {
        return new SottoComponenteType();
    }

    /**
     * Create an instance of {@link ProfiloArchivisticoType.FascicoliSecondari }
     * 
     */
    public ProfiloArchivisticoType.FascicoliSecondari createProfiloArchivisticoTypeFascicoliSecondari() {
        return new ProfiloArchivisticoType.FascicoliSecondari();
    }

}
