/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:46 PM CET
//

package net.datasiel.par.jaxb.stato;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VersioneXMLChiamata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataRichiestaStato" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EsitoGenerale" type="{}EsitoGeneraleType"/>
 *         &lt;element name="EsitoChiamataWS" type="{}EsitoChiamataWSType"/>
 *         &lt;element name="StatoUnitaDocumentaria" type="{}DatiUnitaDocType" minOccurs="0"/>
 *         &lt;element name="XMLRichiesta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "versione", "versioneXMLChiamata", "dataRichiestaStato", "esitoGenerale",
        "esitoChiamataWS", "statoUnitaDocumentaria", "xmlRichiesta" })
@XmlRootElement(name = "StatoConservazione")
public class StatoConservazione {

    @XmlElement(name = "Versione")
    protected String versione;
    @XmlElement(name = "VersioneXMLChiamata")
    protected String versioneXMLChiamata;
    @XmlElement(name = "DataRichiestaStato", required = true)
    protected XMLGregorianCalendar dataRichiestaStato;
    @XmlElement(name = "EsitoGenerale", required = true)
    protected EsitoGeneraleType esitoGenerale;
    @XmlElement(name = "EsitoChiamataWS", required = true)
    protected EsitoChiamataWSType esitoChiamataWS;
    @XmlElement(name = "StatoUnitaDocumentaria")
    protected DatiUnitaDocType statoUnitaDocumentaria;
    @XmlElement(name = "XMLRichiesta")
    protected String xmlRichiesta;

    /**
     * Gets the value of the versione property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersione() {
        return versione;
    }

    /**
     * Sets the value of the versione property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setVersione(String value) {
        this.versione = value;
    }

    /**
     * Gets the value of the versioneXMLChiamata property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersioneXMLChiamata() {
        return versioneXMLChiamata;
    }

    /**
     * Sets the value of the versioneXMLChiamata property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setVersioneXMLChiamata(String value) {
        this.versioneXMLChiamata = value;
    }

    /**
     * Gets the value of the dataRichiestaStato property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataRichiestaStato() {
        return dataRichiestaStato;
    }

    /**
     * Sets the value of the dataRichiestaStato property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataRichiestaStato(XMLGregorianCalendar value) {
        this.dataRichiestaStato = value;
    }

    /**
     * Gets the value of the esitoGenerale property.
     *
     * @return possible object is {@link EsitoGeneraleType }
     *
     */
    public EsitoGeneraleType getEsitoGenerale() {
        return esitoGenerale;
    }

    /**
     * Sets the value of the esitoGenerale property.
     *
     * @param value
     *            allowed object is {@link EsitoGeneraleType }
     *
     */
    public void setEsitoGenerale(EsitoGeneraleType value) {
        this.esitoGenerale = value;
    }

    /**
     * Gets the value of the esitoChiamataWS property.
     *
     * @return possible object is {@link EsitoChiamataWSType }
     *
     */
    public EsitoChiamataWSType getEsitoChiamataWS() {
        return esitoChiamataWS;
    }

    /**
     * Sets the value of the esitoChiamataWS property.
     *
     * @param value
     *            allowed object is {@link EsitoChiamataWSType }
     *
     */
    public void setEsitoChiamataWS(EsitoChiamataWSType value) {
        this.esitoChiamataWS = value;
    }

    /**
     * Gets the value of the statoUnitaDocumentaria property.
     *
     * @return possible object is {@link DatiUnitaDocType }
     *
     */
    public DatiUnitaDocType getStatoUnitaDocumentaria() {
        return statoUnitaDocumentaria;
    }

    /**
     * Sets the value of the statoUnitaDocumentaria property.
     *
     * @param value
     *            allowed object is {@link DatiUnitaDocType }
     *
     */
    public void setStatoUnitaDocumentaria(DatiUnitaDocType value) {
        this.statoUnitaDocumentaria = value;
    }

    /**
     * Gets the value of the xmlRichiesta property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getXMLRichiesta() {
        return xmlRichiesta;
    }

    /**
     * Sets the value of the xmlRichiesta property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setXMLRichiesta(String value) {
        this.xmlRichiesta = value;
    }

}
