/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:46 PM CET
//

package net.datasiel.par.jaxb.stato;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VersioneXMLChiamata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataRichiestaStato" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EsitoGenerale" type="{}EsitoGeneraleType"/>
 *         &lt;element name="EsitoChiamataWS" type="{}EsitoChiamataWSType"/>
 *         &lt;element name="FileInclusiNellaRisposta" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Versatore" type="{}SCVersatoreType" minOccurs="0"/>
 *         &lt;element name="Chiave" type="{}ChiaveType"/>
 *         &lt;element name="TipologiaUnitaDocumentaria" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="DataCreazioneUD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="StatoConservazioneUD" type="{}TokenNonVuotoType"/>
 *         &lt;element name="ProfiloArchivistico" type="{}ProfiloArchivisticoType" minOccurs="0"/>
 *         &lt;element name="ProfiloUnitaDocumentaria" type="{}ProfiloUnitaDocumentariaType" minOccurs="0"/>
 *         &lt;element name="DatiSpecifici" type="{}DatiSpecificiType" minOccurs="0"/>
 *         &lt;element name="DatiSpecificiMigrazione" type="{}DatiSpecificiType" minOccurs="0"/>
 *         &lt;element name="DocumentiCollegati" type="{}DocumentoCollegatoType" minOccurs="0"/>
 *         &lt;element name="NumeroAllegati" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumeroAnnessi" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumeroAnnotazioni" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="DocumentoPrincipale" type="{}DocumentoType"/>
 *         &lt;element name="Allegati" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Allegato" type="{}DocumentoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Annessi" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Annesso" type="{}DocumentoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Annotazioni" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Annotazione" type="{}DocumentoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "versione", "versioneXMLChiamata", "dataRichiestaStato", "esitoGenerale",
        "esitoChiamataWS", "fileInclusiNellaRisposta", "versatore", "chiave", "tipologiaUnitaDocumentaria",
        "dataCreazioneUD", "statoConservazioneUD", "profiloArchivistico", "profiloUnitaDocumentaria", "datiSpecifici",
        "datiSpecificiMigrazione", "documentiCollegati", "numeroAllegati", "numeroAnnessi", "numeroAnnotazioni",
        "documentoPrincipale", "allegati", "annessi", "annotazioni" })
@XmlRootElement(name = "UnitaDocumentaria")
public class UnitaDocumentaria {

    @XmlElement(name = "Versione")
    protected String versione;
    @XmlElement(name = "VersioneXMLChiamata")
    protected String versioneXMLChiamata;
    @XmlElement(name = "DataRichiestaStato", required = true)
    protected XMLGregorianCalendar dataRichiestaStato;
    @XmlElement(name = "EsitoGenerale", required = true)
    protected EsitoGeneraleType esitoGenerale;
    @XmlElement(name = "EsitoChiamataWS", required = true)
    protected EsitoChiamataWSType esitoChiamataWS;
    @XmlElement(name = "FileInclusiNellaRisposta")
    protected boolean fileInclusiNellaRisposta;
    @XmlElement(name = "Versatore")
    protected SCVersatoreType versatore;
    @XmlElement(name = "Chiave", required = true)
    protected ChiaveType chiave;
    @XmlElement(name = "TipologiaUnitaDocumentaria", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipologiaUnitaDocumentaria;
    @XmlElement(name = "DataCreazioneUD", required = true)
    protected XMLGregorianCalendar dataCreazioneUD;
    @XmlElement(name = "StatoConservazioneUD", required = true)
    protected String statoConservazioneUD;
    @XmlElement(name = "ProfiloArchivistico")
    protected ProfiloArchivisticoType profiloArchivistico;
    @XmlElement(name = "ProfiloUnitaDocumentaria")
    protected ProfiloUnitaDocumentariaType profiloUnitaDocumentaria;
    @XmlElement(name = "DatiSpecifici")
    protected DatiSpecificiType datiSpecifici;
    @XmlElement(name = "DatiSpecificiMigrazione")
    protected DatiSpecificiType datiSpecificiMigrazione;
    @XmlElement(name = "DocumentiCollegati")
    protected DocumentoCollegatoType documentiCollegati;
    @XmlElement(name = "NumeroAllegati")
    protected BigInteger numeroAllegati;
    @XmlElement(name = "NumeroAnnessi")
    protected BigInteger numeroAnnessi;
    @XmlElement(name = "NumeroAnnotazioni")
    protected BigInteger numeroAnnotazioni;
    @XmlElement(name = "DocumentoPrincipale", required = true)
    protected DocumentoType documentoPrincipale;
    @XmlElement(name = "Allegati")
    protected UnitaDocumentaria.Allegati allegati;
    @XmlElement(name = "Annessi")
    protected UnitaDocumentaria.Annessi annessi;
    @XmlElement(name = "Annotazioni")
    protected UnitaDocumentaria.Annotazioni annotazioni;

    /**
     * Gets the value of the versione property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersione() {
        return versione;
    }

    /**
     * Sets the value of the versione property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setVersione(String value) {
        this.versione = value;
    }

    /**
     * Gets the value of the versioneXMLChiamata property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersioneXMLChiamata() {
        return versioneXMLChiamata;
    }

    /**
     * Sets the value of the versioneXMLChiamata property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setVersioneXMLChiamata(String value) {
        this.versioneXMLChiamata = value;
    }

    /**
     * Gets the value of the dataRichiestaStato property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataRichiestaStato() {
        return dataRichiestaStato;
    }

    /**
     * Sets the value of the dataRichiestaStato property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataRichiestaStato(XMLGregorianCalendar value) {
        this.dataRichiestaStato = value;
    }

    /**
     * Gets the value of the esitoGenerale property.
     *
     * @return possible object is {@link EsitoGeneraleType }
     *
     */
    public EsitoGeneraleType getEsitoGenerale() {
        return esitoGenerale;
    }

    /**
     * Sets the value of the esitoGenerale property.
     *
     * @param value
     *            allowed object is {@link EsitoGeneraleType }
     *
     */
    public void setEsitoGenerale(EsitoGeneraleType value) {
        this.esitoGenerale = value;
    }

    /**
     * Gets the value of the esitoChiamataWS property.
     *
     * @return possible object is {@link EsitoChiamataWSType }
     *
     */
    public EsitoChiamataWSType getEsitoChiamataWS() {
        return esitoChiamataWS;
    }

    /**
     * Sets the value of the esitoChiamataWS property.
     *
     * @param value
     *            allowed object is {@link EsitoChiamataWSType }
     *
     */
    public void setEsitoChiamataWS(EsitoChiamataWSType value) {
        this.esitoChiamataWS = value;
    }

    /**
     * Gets the value of the fileInclusiNellaRisposta property.
     *
     */
    public boolean isFileInclusiNellaRisposta() {
        return fileInclusiNellaRisposta;
    }

    /**
     * Sets the value of the fileInclusiNellaRisposta property.
     *
     */
    public void setFileInclusiNellaRisposta(boolean value) {
        this.fileInclusiNellaRisposta = value;
    }

    /**
     * Gets the value of the versatore property.
     *
     * @return possible object is {@link SCVersatoreType }
     *
     */
    public SCVersatoreType getVersatore() {
        return versatore;
    }

    /**
     * Sets the value of the versatore property.
     *
     * @param value
     *            allowed object is {@link SCVersatoreType }
     *
     */
    public void setVersatore(SCVersatoreType value) {
        this.versatore = value;
    }

    /**
     * Gets the value of the chiave property.
     *
     * @return possible object is {@link ChiaveType }
     *
     */
    public ChiaveType getChiave() {
        return chiave;
    }

    /**
     * Sets the value of the chiave property.
     *
     * @param value
     *            allowed object is {@link ChiaveType }
     *
     */
    public void setChiave(ChiaveType value) {
        this.chiave = value;
    }

    /**
     * Gets the value of the tipologiaUnitaDocumentaria property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTipologiaUnitaDocumentaria() {
        return tipologiaUnitaDocumentaria;
    }

    /**
     * Sets the value of the tipologiaUnitaDocumentaria property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setTipologiaUnitaDocumentaria(String value) {
        this.tipologiaUnitaDocumentaria = value;
    }

    /**
     * Gets the value of the dataCreazioneUD property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataCreazioneUD() {
        return dataCreazioneUD;
    }

    /**
     * Sets the value of the dataCreazioneUD property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setDataCreazioneUD(XMLGregorianCalendar value) {
        this.dataCreazioneUD = value;
    }

    /**
     * Gets the value of the statoConservazioneUD property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatoConservazioneUD() {
        return statoConservazioneUD;
    }

    /**
     * Sets the value of the statoConservazioneUD property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setStatoConservazioneUD(String value) {
        this.statoConservazioneUD = value;
    }

    /**
     * Gets the value of the profiloArchivistico property.
     *
     * @return possible object is {@link ProfiloArchivisticoType }
     *
     */
    public ProfiloArchivisticoType getProfiloArchivistico() {
        return profiloArchivistico;
    }

    /**
     * Sets the value of the profiloArchivistico property.
     *
     * @param value
     *            allowed object is {@link ProfiloArchivisticoType }
     *
     */
    public void setProfiloArchivistico(ProfiloArchivisticoType value) {
        this.profiloArchivistico = value;
    }

    /**
     * Gets the value of the profiloUnitaDocumentaria property.
     *
     * @return possible object is {@link ProfiloUnitaDocumentariaType }
     *
     */
    public ProfiloUnitaDocumentariaType getProfiloUnitaDocumentaria() {
        return profiloUnitaDocumentaria;
    }

    /**
     * Sets the value of the profiloUnitaDocumentaria property.
     *
     * @param value
     *            allowed object is {@link ProfiloUnitaDocumentariaType }
     *
     */
    public void setProfiloUnitaDocumentaria(ProfiloUnitaDocumentariaType value) {
        this.profiloUnitaDocumentaria = value;
    }

    /**
     * Gets the value of the datiSpecifici property.
     *
     * @return possible object is {@link DatiSpecificiType }
     *
     */
    public DatiSpecificiType getDatiSpecifici() {
        return datiSpecifici;
    }

    /**
     * Sets the value of the datiSpecifici property.
     *
     * @param value
     *            allowed object is {@link DatiSpecificiType }
     *
     */
    public void setDatiSpecifici(DatiSpecificiType value) {
        this.datiSpecifici = value;
    }

    /**
     * Gets the value of the datiSpecificiMigrazione property.
     *
     * @return possible object is {@link DatiSpecificiType }
     *
     */
    public DatiSpecificiType getDatiSpecificiMigrazione() {
        return datiSpecificiMigrazione;
    }

    /**
     * Sets the value of the datiSpecificiMigrazione property.
     *
     * @param value
     *            allowed object is {@link DatiSpecificiType }
     *
     */
    public void setDatiSpecificiMigrazione(DatiSpecificiType value) {
        this.datiSpecificiMigrazione = value;
    }

    /**
     * Gets the value of the documentiCollegati property.
     *
     * @return possible object is {@link DocumentoCollegatoType }
     *
     */
    public DocumentoCollegatoType getDocumentiCollegati() {
        return documentiCollegati;
    }

    /**
     * Sets the value of the documentiCollegati property.
     *
     * @param value
     *            allowed object is {@link DocumentoCollegatoType }
     *
     */
    public void setDocumentiCollegati(DocumentoCollegatoType value) {
        this.documentiCollegati = value;
    }

    /**
     * Gets the value of the numeroAllegati property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getNumeroAllegati() {
        return numeroAllegati;
    }

    /**
     * Sets the value of the numeroAllegati property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setNumeroAllegati(BigInteger value) {
        this.numeroAllegati = value;
    }

    /**
     * Gets the value of the numeroAnnessi property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getNumeroAnnessi() {
        return numeroAnnessi;
    }

    /**
     * Sets the value of the numeroAnnessi property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setNumeroAnnessi(BigInteger value) {
        this.numeroAnnessi = value;
    }

    /**
     * Gets the value of the numeroAnnotazioni property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getNumeroAnnotazioni() {
        return numeroAnnotazioni;
    }

    /**
     * Sets the value of the numeroAnnotazioni property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setNumeroAnnotazioni(BigInteger value) {
        this.numeroAnnotazioni = value;
    }

    /**
     * Gets the value of the documentoPrincipale property.
     *
     * @return possible object is {@link DocumentoType }
     *
     */
    public DocumentoType getDocumentoPrincipale() {
        return documentoPrincipale;
    }

    /**
     * Sets the value of the documentoPrincipale property.
     *
     * @param value
     *            allowed object is {@link DocumentoType }
     *
     */
    public void setDocumentoPrincipale(DocumentoType value) {
        this.documentoPrincipale = value;
    }

    /**
     * Gets the value of the allegati property.
     *
     * @return possible object is {@link UnitaDocumentaria.Allegati }
     *
     */
    public UnitaDocumentaria.Allegati getAllegati() {
        return allegati;
    }

    /**
     * Sets the value of the allegati property.
     *
     * @param value
     *            allowed object is {@link UnitaDocumentaria.Allegati }
     *
     */
    public void setAllegati(UnitaDocumentaria.Allegati value) {
        this.allegati = value;
    }

    /**
     * Gets the value of the annessi property.
     *
     * @return possible object is {@link UnitaDocumentaria.Annessi }
     *
     */
    public UnitaDocumentaria.Annessi getAnnessi() {
        return annessi;
    }

    /**
     * Sets the value of the annessi property.
     *
     * @param value
     *            allowed object is {@link UnitaDocumentaria.Annessi }
     *
     */
    public void setAnnessi(UnitaDocumentaria.Annessi value) {
        this.annessi = value;
    }

    /**
     * Gets the value of the annotazioni property.
     *
     * @return possible object is {@link UnitaDocumentaria.Annotazioni }
     *
     */
    public UnitaDocumentaria.Annotazioni getAnnotazioni() {
        return annotazioni;
    }

    /**
     * Sets the value of the annotazioni property.
     *
     * @param value
     *            allowed object is {@link UnitaDocumentaria.Annotazioni }
     *
     */
    public void setAnnotazioni(UnitaDocumentaria.Annotazioni value) {
        this.annotazioni = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Allegato" type="{}DocumentoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "allegato" })
    public static class Allegati {

        @XmlElement(name = "Allegato", required = true)
        protected List<DocumentoType> allegato;

        /**
         * Gets the value of the allegato property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the allegato property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getAllegato().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DocumentoType }
         *
         *
         */
        public List<DocumentoType> getAllegato() {
            if (allegato == null) {
                allegato = new ArrayList<DocumentoType>();
            }
            return this.allegato;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Annesso" type="{}DocumentoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "annesso" })
    public static class Annessi {

        @XmlElement(name = "Annesso", required = true)
        protected List<DocumentoType> annesso;

        /**
         * Gets the value of the annesso property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the annesso property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getAnnesso().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DocumentoType }
         *
         *
         */
        public List<DocumentoType> getAnnesso() {
            if (annesso == null) {
                annesso = new ArrayList<DocumentoType>();
            }
            return this.annesso;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Annotazione" type="{}DocumentoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "annotazione" })
    public static class Annotazioni {

        @XmlElement(name = "Annotazione", required = true)
        protected List<DocumentoType> annotazione;

        /**
         * Gets the value of the annotazione property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the annotazione property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getAnnotazione().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DocumentoType }
         *
         *
         */
        public List<DocumentoType> getAnnotazione() {
            if (annotazione == null) {
                annotazione = new ArrayList<DocumentoType>();
            }
            return this.annotazione;
        }

    }

}
