/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 02:20:31 PM CET 
//

package net.datasiel.par.jaxb.versamento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for ConfigType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoConservazione" type="{}TipoConservazioneType" minOccurs="0"/>
 *         &lt;element name="SistemaDiMigrazione" type="{}TokenNVMax100Type" minOccurs="0"/>
 *         &lt;element name="ForzaAccettazione" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ForzaConservazione" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ForzaCollegamento" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SimulaSalvataggioDatiInDB" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigType", propOrder = { "tipoConservazione", "sistemaDiMigrazione", "forzaAccettazione",
        "forzaConservazione", "forzaCollegamento", "simulaSalvataggioDatiInDB" })
public class ConfigType {

    @XmlElement(name = "TipoConservazione")
    protected TipoConservazioneType tipoConservazione;
    @XmlElement(name = "SistemaDiMigrazione")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sistemaDiMigrazione;
    @XmlElement(name = "ForzaAccettazione")
    protected Boolean forzaAccettazione;
    @XmlElement(name = "ForzaConservazione")
    protected Boolean forzaConservazione;
    @XmlElement(name = "ForzaCollegamento")
    protected Boolean forzaCollegamento;
    @XmlElement(name = "SimulaSalvataggioDatiInDB")
    protected Boolean simulaSalvataggioDatiInDB;

    /**
     * Gets the value of the tipoConservazione property.
     * 
     * @return possible object is {@link TipoConservazioneType }
     * 
     */
    public TipoConservazioneType getTipoConservazione() {
        return tipoConservazione;
    }

    /**
     * Sets the value of the tipoConservazione property.
     * 
     * @param value
     *            allowed object is {@link TipoConservazioneType }
     * 
     */
    public void setTipoConservazione(TipoConservazioneType value) {
        this.tipoConservazione = value;
    }

    /**
     * Gets the value of the sistemaDiMigrazione property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSistemaDiMigrazione() {
        return sistemaDiMigrazione;
    }

    /**
     * Sets the value of the sistemaDiMigrazione property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSistemaDiMigrazione(String value) {
        this.sistemaDiMigrazione = value;
    }

    /**
     * Gets the value of the forzaAccettazione property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isForzaAccettazione() {
        return forzaAccettazione;
    }

    /**
     * Sets the value of the forzaAccettazione property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setForzaAccettazione(Boolean value) {
        this.forzaAccettazione = value;
    }

    /**
     * Gets the value of the forzaConservazione property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isForzaConservazione() {
        return forzaConservazione;
    }

    /**
     * Sets the value of the forzaConservazione property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setForzaConservazione(Boolean value) {
        this.forzaConservazione = value;
    }

    /**
     * Gets the value of the forzaCollegamento property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isForzaCollegamento() {
        return forzaCollegamento;
    }

    /**
     * Sets the value of the forzaCollegamento property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setForzaCollegamento(Boolean value) {
        this.forzaCollegamento = value;
    }

    /**
     * Gets the value of the simulaSalvataggioDatiInDB property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSimulaSalvataggioDatiInDB() {
        return simulaSalvataggioDatiInDB;
    }

    /**
     * Sets the value of the simulaSalvataggioDatiInDB property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSimulaSalvataggioDatiInDB(Boolean value) {
        this.simulaSalvataggioDatiInDB = value;
    }

}
