/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 02:20:31 PM CET
//

package net.datasiel.par.jaxb.versamento;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DocumentoCollegatoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentoCollegatoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoCollegato" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ChiaveCollegamento" type="{}ChiaveType"/>
 *                   &lt;element name="DescrizioneCollegamento" type="{}StringMax254Type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentoCollegatoType", propOrder = { "documentoCollegato" })
public class DocumentoCollegatoType {

    @XmlElement(name = "DocumentoCollegato", required = true)
    protected List<DocumentoCollegatoType.DocumentoCollegato> documentoCollegato;

    /**
     * Gets the value of the documentoCollegato property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the documentoCollegato property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDocumentoCollegato().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DocumentoCollegatoType.DocumentoCollegato }
     *
     *
     */
    public List<DocumentoCollegatoType.DocumentoCollegato> getDocumentoCollegato() {
        if (documentoCollegato == null) {
            documentoCollegato = new ArrayList<DocumentoCollegatoType.DocumentoCollegato>();
        }
        return this.documentoCollegato;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ChiaveCollegamento" type="{}ChiaveType"/>
     *         &lt;element name="DescrizioneCollegamento" type="{}StringMax254Type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "chiaveCollegamento", "descrizioneCollegamento" })
    public static class DocumentoCollegato {

        @XmlElement(name = "ChiaveCollegamento", required = true)
        protected ChiaveType chiaveCollegamento;
        @XmlElement(name = "DescrizioneCollegamento", required = true)
        protected String descrizioneCollegamento;

        /**
         * Gets the value of the chiaveCollegamento property.
         *
         * @return possible object is {@link ChiaveType }
         *
         */
        public ChiaveType getChiaveCollegamento() {
            return chiaveCollegamento;
        }

        /**
         * Sets the value of the chiaveCollegamento property.
         *
         * @param value
         *            allowed object is {@link ChiaveType }
         *
         */
        public void setChiaveCollegamento(ChiaveType value) {
            this.chiaveCollegamento = value;
        }

        /**
         * Gets the value of the descrizioneCollegamento property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getDescrizioneCollegamento() {
            return descrizioneCollegamento;
        }

        /**
         * Sets the value of the descrizioneCollegamento property.
         *
         * @param value
         *            allowed object is {@link String }
         *
         */
        public void setDescrizioneCollegamento(String value) {
            this.descrizioneCollegamento = value;
        }

    }

}
