/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 02:20:31 PM CET 
//

package net.datasiel.par.jaxb.versamento;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for StrutturaType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StrutturaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoStruttura" type="{}TokenNonVuotoType" minOccurs="0"/>
 *         &lt;element name="Componenti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Componente" type="{}ComponenteType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StrutturaType", propOrder = { "tipoStruttura", "componenti" })
public class StrutturaType {

    @XmlElement(name = "TipoStruttura")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipoStruttura;
    @XmlElement(name = "Componenti", required = true)
    protected StrutturaType.Componenti componenti;

    /**
     * Gets the value of the tipoStruttura property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTipoStruttura() {
        return tipoStruttura;
    }

    /**
     * Sets the value of the tipoStruttura property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTipoStruttura(String value) {
        this.tipoStruttura = value;
    }

    /**
     * Gets the value of the componenti property.
     * 
     * @return possible object is {@link StrutturaType.Componenti }
     * 
     */
    public StrutturaType.Componenti getComponenti() {
        return componenti;
    }

    /**
     * Sets the value of the componenti property.
     * 
     * @param value
     *            allowed object is {@link StrutturaType.Componenti }
     * 
     */
    public void setComponenti(StrutturaType.Componenti value) {
        this.componenti = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Componente" type="{}ComponenteType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "componente" })
    public static class Componenti {

        @XmlElement(name = "Componente", required = true)
        protected List<ComponenteType> componente;

        /**
         * Gets the value of the componente property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the componente property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getComponente().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link ComponenteType }
         * 
         * 
         */
        public List<ComponenteType> getComponente() {
            if (componente == null) {
                componente = new ArrayList<ComponenteType>();
            }
            return this.componente;
        }

    }

}
