/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 02:20:31 PM CET
//

package net.datasiel.par.jaxb.versamento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Intestazione" type="{}IntestazioneAggAllType"/>
 *         &lt;element name="Configurazione" type="{}ConfigAggAllType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Allegato" type="{}DocumentoType"/>
 *           &lt;element name="Annesso" type="{}DocumentoType"/>
 *           &lt;element name="Annotazione" type="{}DocumentoType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "intestazione", "configurazione", "allegato", "annesso", "annotazione" })
@XmlRootElement(name = "UnitaDocAggAllegati")
public class UnitaDocAggAllegati {

    @XmlElement(name = "Intestazione", required = true)
    protected IntestazioneAggAllType intestazione;
    @XmlElement(name = "Configurazione")
    protected ConfigAggAllType configurazione;
    @XmlElement(name = "Allegato")
    protected DocumentoType allegato;
    @XmlElement(name = "Annesso")
    protected DocumentoType annesso;
    @XmlElement(name = "Annotazione")
    protected DocumentoType annotazione;

    /**
     * Gets the value of the intestazione property.
     *
     * @return possible object is {@link IntestazioneAggAllType }
     *
     */
    public IntestazioneAggAllType getIntestazione() {
        return intestazione;
    }

    /**
     * Sets the value of the intestazione property.
     *
     * @param value
     *            allowed object is {@link IntestazioneAggAllType }
     *
     */
    public void setIntestazione(IntestazioneAggAllType value) {
        this.intestazione = value;
    }

    /**
     * Gets the value of the configurazione property.
     *
     * @return possible object is {@link ConfigAggAllType }
     *
     */
    public ConfigAggAllType getConfigurazione() {
        return configurazione;
    }

    /**
     * Sets the value of the configurazione property.
     *
     * @param value
     *            allowed object is {@link ConfigAggAllType }
     *
     */
    public void setConfigurazione(ConfigAggAllType value) {
        this.configurazione = value;
    }

    /**
     * Gets the value of the allegato property.
     *
     * @return possible object is {@link DocumentoType }
     *
     */
    public DocumentoType getAllegato() {
        return allegato;
    }

    /**
     * Sets the value of the allegato property.
     *
     * @param value
     *            allowed object is {@link DocumentoType }
     *
     */
    public void setAllegato(DocumentoType value) {
        this.allegato = value;
    }

    /**
     * Gets the value of the annesso property.
     *
     * @return possible object is {@link DocumentoType }
     *
     */
    public DocumentoType getAnnesso() {
        return annesso;
    }

    /**
     * Sets the value of the annesso property.
     *
     * @param value
     *            allowed object is {@link DocumentoType }
     *
     */
    public void setAnnesso(DocumentoType value) {
        this.annesso = value;
    }

    /**
     * Gets the value of the annotazione property.
     *
     * @return possible object is {@link DocumentoType }
     *
     */
    public DocumentoType getAnnotazione() {
        return annotazione;
    }

    /**
     * Sets the value of the annotazione property.
     *
     * @param value
     *            allowed object is {@link DocumentoType }
     *
     */
    public void setAnnotazione(DocumentoType value) {
        this.annotazione = value;
    }

}
