/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:57 PM CET
//

package net.datasiel.par.jaxb.esito;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for ECEsitoControlloType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="ECEsitoControlloType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="POSITIVO"/>
 *     &lt;enumeration value="NEGATIVO"/>
 *     &lt;enumeration value="WARNING"/>
 *     &lt;enumeration value="NON_ESEGUITO"/>
 *     &lt;enumeration value="FORMATO_NON_CONOSCIUTO"/>
 *     &lt;enumeration value="FORMATO_NON_CONFORME"/>
 *     &lt;enumeration value="NON_AMMESSO_DELIB_45_CNIPA"/>
 *     &lt;enumeration value="DISABILITATO"/>
 *     &lt;enumeration value="NON_NECESSARIO"/>
 *     &lt;enumeration value="ERRORE"/>
 *     &lt;enumeration value="CERTIFICATO_ERRATO"/>
 *     &lt;enumeration value="CERTIFICATO_NON_VALIDO"/>
 *     &lt;enumeration value="CERTIFICATO_REVOCATO"/>
 *     &lt;enumeration value="CERTIFICATO_SCADUTO"/>
 *     &lt;enumeration value="CERTIFICATO_SCADUTO_3_12_2009"/>
 *     &lt;enumeration value="CRL_NON_SCARICABILE"/>
 *     &lt;enumeration value="CRL_NON_VALIDA"/>
 *     &lt;enumeration value="CRL_SCADUTA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlEnum
public enum ECEsitoControlloType {

    POSITIVO, NEGATIVO, WARNING, NON_ESEGUITO, FORMATO_NON_CONOSCIUTO, FORMATO_NON_CONFORME, NON_AMMESSO_DELIB_45_CNIPA,
    DISABILITATO, NON_NECESSARIO, ERRORE, CERTIFICATO_ERRATO, CERTIFICATO_NON_VALIDO, CERTIFICATO_REVOCATO,
    CERTIFICATO_SCADUTO, CERTIFICATO_SCADUTO_3_12_2009, CRL_NON_SCARICABILE, CRL_NON_VALIDA, CRL_SCADUTA;

    public String value() {
        return name();
    }

    public static ECEsitoControlloType fromValue(String v) {
        return valueOf(v);
    }

}
