/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:57 PM CET
//

package net.datasiel.par.jaxb.esito;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ECEsitoGeneraleType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ECEsitoGeneraleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodiceEsito" type="{}ECEsitoExtType"/>
 *         &lt;element name="CodiceErrore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MessaggioErrore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECEsitoGeneraleType", propOrder = { "codiceEsito", "codiceErrore", "messaggioErrore" })
public class ECEsitoGeneraleType {

    @XmlElement(name = "CodiceEsito", required = true)
    protected ECEsitoExtType codiceEsito;
    @XmlElement(name = "CodiceErrore")
    protected String codiceErrore;
    @XmlElement(name = "MessaggioErrore")
    protected String messaggioErrore;

    /**
     * Gets the value of the codiceEsito property.
     *
     * @return possible object is {@link ECEsitoExtType }
     *
     */
    public ECEsitoExtType getCodiceEsito() {
        return codiceEsito;
    }

    /**
     * Sets the value of the codiceEsito property.
     *
     * @param value
     *            allowed object is {@link ECEsitoExtType }
     *
     */
    public void setCodiceEsito(ECEsitoExtType value) {
        this.codiceEsito = value;
    }

    /**
     * Gets the value of the codiceErrore property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCodiceErrore() {
        return codiceErrore;
    }

    /**
     * Sets the value of the codiceErrore property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setCodiceErrore(String value) {
        this.codiceErrore = value;
    }

    /**
     * Gets the value of the messaggioErrore property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessaggioErrore() {
        return messaggioErrore;
    }

    /**
     * Sets the value of the messaggioErrore property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMessaggioErrore(String value) {
        this.messaggioErrore = value;
    }

}
