/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 03:12:57 PM CET 
//

package net.datasiel.par.jaxb.esito;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for ECStatoConsType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ECStatoConsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="IN_ATTESA_SCHED"/>
 *     &lt;enumeration value="IN_VOLUME_APERTO"/>
 *     &lt;enumeration value="IN_VOLUME_CHIUSO"/>
 *     &lt;enumeration value="IN_VOLUME_IN_ERRORE"/>
 *     &lt;enumeration value="NON_SELEZ_SCHED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ECStatoConsType {

    IN_ATTESA_SCHED, IN_VOLUME_APERTO, IN_VOLUME_CHIUSO, IN_VOLUME_IN_ERRORE, NON_SELEZ_SCHED;

    public String value() {
        return name();
    }

    public static ECStatoConsType fromValue(String v) {
        return valueOf(v);
    }

}
