/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 03:12:57 PM CET
//

package net.datasiel.par.jaxb.esito;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.datasiel.par.jaxb.esito package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.datasiel.par.jaxb.esito
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ECMarcaType.EsitoMarca.VerificaMarca }
     *
     */
    public ECMarcaType.EsitoMarca.VerificaMarca createECMarcaTypeEsitoMarcaVerificaMarca() {
        return new ECMarcaType.EsitoMarca.VerificaMarca();
    }

    /**
     * Create an instance of {@link ECUnitaDocType.Annessi }
     *
     */
    public ECUnitaDocType.Annessi createECUnitaDocTypeAnnessi() {
        return new ECUnitaDocType.Annessi();
    }

    /**
     * Create an instance of {@link SCChiaveType }
     *
     */
    public SCChiaveType createSCChiaveType() {
        return new SCChiaveType();
    }

    /**
     * Create an instance of {@link ECUnitaDocType.Annotazioni }
     *
     */
    public ECUnitaDocType.Annotazioni createECUnitaDocTypeAnnotazioni() {
        return new ECUnitaDocType.Annotazioni();
    }

    /**
     * Create an instance of {@link ECFirmatarioType.EsitoFirma }
     *
     */
    public ECFirmatarioType.EsitoFirma createECFirmatarioTypeEsitoFirma() {
        return new ECFirmatarioType.EsitoFirma();
    }

    /**
     * Create an instance of {@link EsitoVersAggAllegati }
     *
     */
    public EsitoVersAggAllegati createEsitoVersAggAllegati() {
        return new EsitoVersAggAllegati();
    }

    /**
     * Create an instance of {@link ECUnitaDocType.EsitoUnitaDocumentaria }
     *
     */
    public ECUnitaDocType.EsitoUnitaDocumentaria createECUnitaDocTypeEsitoUnitaDocumentaria() {
        return new ECUnitaDocType.EsitoUnitaDocumentaria();
    }

    /**
     * Create an instance of {@link ECDocumentoType }
     *
     */
    public ECDocumentoType createECDocumentoType() {
        return new ECDocumentoType();
    }

    /**
     * Create an instance of {@link EsitoVersamento }
     *
     */
    public EsitoVersamento createEsitoVersamento() {
        return new EsitoVersamento();
    }

    /**
     * Create an instance of {@link ECSottoComponenteType }
     *
     */
    public ECSottoComponenteType createECSottoComponenteType() {
        return new ECSottoComponenteType();
    }

    /**
     * Create an instance of {@link ECConfigurazioneType }
     *
     */
    public ECConfigurazioneType createECConfigurazioneType() {
        return new ECConfigurazioneType();
    }

    /**
     * Create an instance of {@link ECComponenteType.EsitoComponente }
     *
     */
    public ECComponenteType.EsitoComponente createECComponenteTypeEsitoComponente() {
        return new ECComponenteType.EsitoComponente();
    }

    /**
     * Create an instance of {@link ECUnitaDocType.Allegati }
     *
     */
    public ECUnitaDocType.Allegati createECUnitaDocTypeAllegati() {
        return new ECUnitaDocType.Allegati();
    }

    /**
     * Create an instance of {@link SCVersatoreType }
     *
     */
    public SCVersatoreType createSCVersatoreType() {
        return new SCVersatoreType();
    }

    /**
     * Create an instance of {@link ECFirmatarioType.EsitoFirma.VerificaFirma }
     *
     */
    public ECFirmatarioType.EsitoFirma.VerificaFirma createECFirmatarioTypeEsitoFirmaVerificaFirma() {
        return new ECFirmatarioType.EsitoFirma.VerificaFirma();
    }

    /**
     * Create an instance of {@link ECDocumentoType.Componenti }
     *
     */
    public ECDocumentoType.Componenti createECDocumentoTypeComponenti() {
        return new ECDocumentoType.Componenti();
    }

    /**
     * Create an instance of {@link ECComponenteType.Firmatari }
     *
     */
    public ECComponenteType.Firmatari createECComponenteTypeFirmatari() {
        return new ECComponenteType.Firmatari();
    }

    /**
     * Create an instance of {@link ECUnitaDocAggAllType }
     *
     */
    public ECUnitaDocAggAllType createECUnitaDocAggAllType() {
        return new ECUnitaDocAggAllType();
    }

    /**
     * Create an instance of {@link ECUnitaDocAggAllType.EsitoUnitaDocumentaria }
     *
     */
    public ECUnitaDocAggAllType.EsitoUnitaDocumentaria createECUnitaDocAggAllTypeEsitoUnitaDocumentaria() {
        return new ECUnitaDocAggAllType.EsitoUnitaDocumentaria();
    }

    /**
     * Create an instance of {@link ECUnitaDocType }
     *
     */
    public ECUnitaDocType createECUnitaDocType() {
        return new ECUnitaDocType();
    }

    /**
     * Create an instance of {@link ECComponenteType.SottoComponenti }
     *
     */
    public ECComponenteType.SottoComponenti createECComponenteTypeSottoComponenti() {
        return new ECComponenteType.SottoComponenti();
    }

    /**
     * Create an instance of {@link ECMarcaType }
     *
     */
    public ECMarcaType createECMarcaType() {
        return new ECMarcaType();
    }

    /**
     * Create an instance of {@link ECEsitoChiamataWSType }
     *
     */
    public ECEsitoChiamataWSType createECEsitoChiamataWSType() {
        return new ECEsitoChiamataWSType();
    }

    /**
     * Create an instance of {@link ECEsitoXSDAggAllType }
     *
     */
    public ECEsitoXSDAggAllType createECEsitoXSDAggAllType() {
        return new ECEsitoXSDAggAllType();
    }

    /**
     * Create an instance of {@link ECFirmatarioType }
     *
     */
    public ECFirmatarioType createECFirmatarioType() {
        return new ECFirmatarioType();
    }

    /**
     * Create an instance of {@link ECDocumentoType.EsitoDocumento }
     *
     */
    public ECDocumentoType.EsitoDocumento createECDocumentoTypeEsitoDocumento() {
        return new ECDocumentoType.EsitoDocumento();
    }

    /**
     * Create an instance of {@link ECEsitoXSDType }
     *
     */
    public ECEsitoXSDType createECEsitoXSDType() {
        return new ECEsitoXSDType();
    }

    /**
     * Create an instance of {@link ECEsitoGeneraleType }
     *
     */
    public ECEsitoGeneraleType createECEsitoGeneraleType() {
        return new ECEsitoGeneraleType();
    }

    /**
     * Create an instance of {@link ECMarcaType.EsitoMarca }
     *
     */
    public ECMarcaType.EsitoMarca createECMarcaTypeEsitoMarca() {
        return new ECMarcaType.EsitoMarca();
    }

    /**
     * Create an instance of {@link ECComponenteType.Marche }
     *
     */
    public ECComponenteType.Marche createECComponenteTypeMarche() {
        return new ECComponenteType.Marche();
    }

    /**
     * Create an instance of {@link ECComponenteType }
     *
     */
    public ECComponenteType createECComponenteType() {
        return new ECComponenteType();
    }

    /**
     * Create an instance of {@link ECSottoComponenteType.EsitoSottoComponente }
     *
     */
    public ECSottoComponenteType.EsitoSottoComponente createECSottoComponenteTypeEsitoSottoComponente() {
        return new ECSottoComponenteType.EsitoSottoComponente();
    }

}
